### ISSUE TITLE
Some constructive criticism 

### ISSUE THREAD

**Issue by doitonlinemedia** [pespantelis/vue-videobg#1]
Rewrite your html classes to 'video-background' and the Video__content to just 'content'. Content is already nested, no need to prefix it.

See also: https://css-tricks.com/semantic-class-names/

Nice component.

**Comment by pespantelis** [comment]
I follow the `BEM (Block Element Modifier)` methodology. IMO it improves the readability of stylesheets.
https://css-tricks.com/bem-101/

For example, if you want to add an overlay:

``` css
/* with BEM */
.VideoBg__content {}

/* instead of */
.video-bg .content {}
```

Thanks for the interest @doitonlinemedia!

**Comment by shivampesitbng** [comment]
i cannot change the height of the video , although width is changing :(
