### ISSUE TITLE
video not played in iOS devices

### ISSUE THREAD

**Issue by panquela** [pespantelis/vue-videobg#18]
Dear colleague,

The current release of vue-videobg can't play video over iOS devices (any browser over iPhone or iPad)

In order to get videos played properly over the Apple devices, the option 'playsinline' must be included in the video tag. 

Thus, the code of video tag would be as follows:

`<video autoplay loop muted playsinline ref="video">`

We have succesfully tested this change over iphone 5,6,X,XS, iPad & iPad Pro.

Kind regards

Pedro

**Comment by smeranda** [comment]
Looks like this was taken care of a while ago with: 68c5fc6ce23727a7d4d5dd4242076ac45304e22b.

**Comment by shershen** [comment]
Hello!
hm.....

"vue-videobg": "^2.0.0",

`<video autoplay loop muted ref="video">`

where 'playsinline '?

Install from NPM

**Comment by shershen** [comment]
Install from NPM

**Comment by panquela** [comment]
Thanks smeranda for your comment. As you point the issue with Safari and IOS 10+ was correctly documented in [68c5fc6](https://github.com/pespantelis/vue-videobg/commit/68c5fc6ce23727a7d4d5dd4242076ac45304e22b)

Kind regards

**Comment by sebastianjung** [comment]
The playsinline attribute is still missing on a fresh installation with npm. I'm not sure why this happens as the playsinline is perfectly fine on the source code on github.

![image](https://user-images.githubusercontent.com/17472892/81903268-ce43d480-95c1-11ea-8881-eee330936623.png)

![image](https://user-images.githubusercontent.com/17472892/81903304-e4519500-95c1-11ea-9ea9-92b69339c63b.png)

**Comment by platform-kit** [comment]
I've run into this bug today, too. Any workaround?

**Comment by platform-kit** [comment]
Perhaps the code on NPM is not up to date?

Edit: indeed that's the case. To solve - install directly from github with  `npm i pespantelis/vue-videobg`
