### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by inssitu** [pespantelis/vue-videobg#2]
Hi, the components looks great!
Thanks to publish it!

I don't not why but I'm having a problem:

```
gulp-notify: [Laravel Elixir] Browserify Failed!: Unexpected token

.../node_modules/vue-videobg/src/VideoBackground.vue:1
<template>
^
ParseError: Unexpected token
```

If I copy the component outside of the package of node_modules folder it's working...

**Comment by pespantelis** [comment]
Thanks!
