### ISSUE TITLE
Responsive behaviour

### ISSUE THREAD

**Issue by lpeterke** [pespantelis/vue-videobg#3]
Usually you want to reduce the pageload on mobile devices. On top of that the user's viewport probably isn't 16:9 on a smartphone.

It would be great if you could specify a second image that will be displayed instead of the video on smaller viewports and a property to define the minimum width in pixels for the desktop behaviour.

**Comment by pespantelis** [comment]
The `img` prop has used to set an image background to the `section.VideoBg` element. You could achieve that you want by using CSS media queries.

Also, I think to remove the `img` prop. :)

**Comment by lpeterke** [comment]
Oh yes, solving this via CSS and Media Queries entirely is the smartest solution.

**Comment by pespantelis** [comment]
For somehow, my response has disappeared:

> The `img` prop has used to set an image background to the `section.VideoBg` element. You could achieve that you want by using CSS media queries.
> 
> Also, I think to remove the `img` prop. :)
