### ISSUE TITLE
support vue2.0 

### ISSUE THREAD

**Issue by guntertien** [pespantelis/vue-videobg#4]
When to update to  support vue2.0?

**Comment by gtzalavras** [comment]
I think that you can do it by yourself @guntertien.

In VideoBackground.vue do the following:

1.Replace in line 3 the **v-el** attribute by the attribute **ref**. The v-el attribute is not supported in Vue.js v2. See this: [https://vuejs.org/v2/guide/migration.html#v-el-and-v-ref-replaced](url)
Code example:
`<video autoplay loop muted ref="video">`

2.Replace also the function **ready()** by the function **mounted()**. Ready has been replaced by mounted.See this: [https://vuejs.org/v2/guide/migration.html#ready-replaced](url)

3.Replace also all the **$els** by **$refs**.

**Comment by lmartins** [comment]
Can confirm the steps described above do fix the issue.
@pespantelis do you want a PR with these applied?

**Comment by danialhr** [comment]
Did anyone get this to work on vue2.0? 
Anyone able to share your approach on jsfiddle?

**Comment by OwenMelbz** [comment]
Theres been a PR opened all week https://github.com/pespantelis/vue-videobg/pull/5

**Comment by pespantelis** [comment]
Thanks guys!
